# Site settings
title: Alberto Silva Portfolio
email: asilvadesigns@gmail.com
my_name: Alberto Silva
my_skill: Web Designer
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "/portfolio" # the subpath of your site, e.g. /blog/
url: "http://asilvadesigns.com"
# twitter_username: jekyllrb
# github_username:  jekyll

# Build settings
markdown: kramdown

kramdown:
  auto_ids: false

gems:
- jekyll-compass