# Site settings
title: Alberto Silva Portfolio
email: asilvadesigns@gmail.com
phone: (301) 275-0678
my_name: Alberto Silva
my_skill: Designer
description: "Alberto Silva is a graphics and web designer obsessed with complex pattern abstraction que es fluido en español"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://albertosilva.me/"
# twitter_username: jekyllrb
# github_username:  jekyll

# Build settings
permalink: /:categories/:title.html
markdown: kramdown

kramdown:
  auto_ids: false

gems:
- jekyll-compass
# - octopress-minify-html