# Site settings
title: Test
email: asilvadesigns@gmail.com
my_name: Alberto Silva Jr.
my_skill: Web Designer
description: > # this means to ignore newlines until "baseurl:"
  I'm a web designer based out of Germantown, Maryland. I love Jesus, my wife, our newborn son, and ff Mark. When I'm away from my computer I can be found preaching, hiking, or trying to dunk a basketball.
baseurl: "/portfolio/" # the subpath of your site, e.g. /blog/
url: "http://asilvadesigns.com"
# twitter_username: jekyllrb
# github_username:  jekyll

# Build settings
markdown: kramdown

kramdown:
  auto_ids: false

gems:
- jekyll-compass