# Site settings
title: Alberto Silva Portfolio
email: asilvadesigns@gmail.com
my_name: Alberto Silva Jr.
my_skill: Web Designer
description: > # this means to ignore newlines until "baseurl:"
  Alberto Silva is a graphics and web designer obsessed with complex pattern abstraction que es fluido en español.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://asilvadesigns.com"
# twitter_username: jekyllrb
# github_username:  jekyll

# Build settings
permalink: /:categories/:title.html
markdown: kramdown

kramdown:
  auto_ids: false

gems:
- jekyll-compass